# Generated by Django 2.1 on 2018-09-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20, verbose_name='카테고리명')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_star', models.IntegerField(verbose_name='가격 만족도')),
                ('taste_star', models.IntegerField(verbose_name='맛 만족도')),
                ('clean_star', models.IntegerField(verbose_name='청결성 만족도')),
                ('content', models.CharField(max_length=20, verbose_name='20자평')),
                ('try_again', models.TextField(choices=[('꼭 다시 먹는다', '꼭 다시 먹는다'), ('잘 모르겠다', '잘 모르겠다'), ('절대 안 먹는다', '절대 안 먹는다')], verbose_name='다시 먹을 지 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_category', models.CharField(max_length=20, verbose_name='음식 종류(밥, 국, 주류...)')),
                ('dish_name', models.CharField(max_length=20, verbose_name='음식명')),
                ('dish_price', models.IntegerField(verbose_name='음식 가격')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='음식점 이름')),
                ('open_to_close', models.IntegerField(blank=True, verbose_name='오픈 & 마감')),
                ('is_package_possible', models.TextField(choices=[('가능', '가능'), ('불가능', '불가능')], verbose_name='포장 가능 여부')),
                ('is_delivery_possible', models.TextField(choices=[('가능', '가능'), ('불가능', '불가능')], verbose_name='배달 가능 여부')),
                ('is_eating_lonely_possible', models.TextField(choices=[('가능', '가능'), ('불가능', '불가능')], verbose_name='혼밥 가능 여부')),
                ('detail', models.TextField(blank=True, verbose_name='음식점 설명')),
                ('register', models.DateTimeField(auto_now_add=True, verbose_name='음식점 등록일')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.Category', verbose_name='카테고리')),
                ('menu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.Menu', verbose_name='음식점 메뉴')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='dish_eaten',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.Menu', verbose_name='먹은 음식'),
        ),
        migrations.AddField(
            model_name='comment',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Restaurant', verbose_name='해당 가게,'),
        ),
    ]
