# Generated by Django 2.1 on 2018-10-01 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_auto_20181001_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.Restaurant', verbose_name='해당 가게'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='open_to_close',
            field=models.TextField(blank=True, verbose_name='오픈 & 마감'),
        ),
    ]
