# Generated by Django 2.1 on 2018-10-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_auto_20181001_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='카테고리 사진'),
        ),
    ]
