# Generated by Django 2.1 on 2018-10-10 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_auto_20181010_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=110, verbose_name='100자평'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dish_eaten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.Menu', verbose_name='먹은 음식'),
        ),
    ]
