# Generated by Django 2.1 on 2018-10-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0008_auto_20181017_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='is_delivery_possible',
            field=models.TextField(blank=True, choices=[('O', 'O'), ('X', 'X'), ('-', '-')], verbose_name='배달 가능 여부'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_eating_lonely_possible',
            field=models.TextField(blank=True, choices=[('O', 'O'), ('X', 'X'), ('-', '-')], verbose_name='혼밥 가능 여부'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_package_possible',
            field=models.TextField(blank=True, choices=[('O', 'O'), ('X', 'X'), ('-', '-')], verbose_name='포장 가능 여부'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(max_length=12, verbose_name='음식점 이름'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, verbose_name='음식점 전화번호'),
        ),
    ]
