# Generated by Django 2.1 on 2018-11-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0012_auto_20181107_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='150자평'),
        ),
    ]
