# Generated by Django 2.1 on 2018-11-07 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0013_auto_20181107_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dish_eaten',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.Menu', verbose_name='먹은 음식'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='try_again',
            field=models.TextField(blank=True, choices=[('꼭 다시 먹는다', '꼭 다시 먹는다'), ('잘 모르겠다', '잘 모르겠다'), ('절대 안 먹는다', '절대 안 먹는다')], null=True, verbose_name='다시 먹을 지 여부'),
        ),
    ]
