# Generated by Django 2.1 on 2018-11-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0014_auto_20181107_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='dish_eaten',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='먹은 음식'),
        ),
    ]
