# Generated by Django 2.1 on 2018-11-09 10:00

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0016_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='food_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='blog/%Y/%m/%d'),
        ),
    ]
