# Generated by Django 2.1 on 2018-11-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0017_auto_20181109_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='is_eating_lonely_possible',
            field=models.TextField(blank=True, choices=[('O', 'O'), ('X', 'X'), ('-', '-')], verbose_name='카드 가능 여부'),
        ),
    ]
